### ISSUE TITLE
Feature Request: Add Option To Hide Sidebar

### ISSUE THREAD

**Issue by Saroufim** [Foldex/AdwSteamGtk#17]
The sidebar can be a bit redundant and it would be more simplistic to remove it if possible.

**Comment by Foldex** [comment]
This issue is better suited for the upstream theme.

With that said, I don't like an option to remove the sidebar entirely, as some functionality is found only inside of it.  Worse still it's possible to initiate search filters from other areas of the client, but disabling them requires the sidebar. It's entirely possible to soft-lock yourself like that.

What would be preferable is an option to make the sidebar hide when not in use, and expand on either hovering the  left edge of the screen or when focus is brought to it from elsewhere.

The only issue with that is that steam starts with the sidebar focused, so you'd either need to click once somewhere else to hide it, or we'd have to not apply the focus selector. Without the focus selector, anything that brings focus to the sidebar without you explicitly hovering it (e.g. initiating a search filter) would not expand the sidebar into view, which is fairly poor UX wise.

Both are kind of compromises.

**Comment by Foldex** [comment]
Well after playing with it a bit, looks like including focus is a no go, as it gets reset back to the sidebar far too often to be feasible. Guess hover only will have to suffice.

Closing this, as I opened a PR upstream: https://github.com/tkashkin/Adwaita-for-Steam/pull/130
