### ISSUE TITLE
Feature Request: GNOME style app icon

### ISSUE THREAD

**Issue by bragefuglseth** [Foldex/AdwSteamGtk#45]
Hi there! I think AdwSteamGtk would benefit from an app icon following GNOME's [distinct visual style](https://developer.gnome.org/hig/guidelines/app-icons.html). This would make it look more at home in the GNOME ecosystem, and make it visible at a glance as an app targeting GNOME.

I can assist with designing one if you want me to. Feel free to reach out to us in the [GNOME App Icon Design group](https://matrix.to/#/#appicondesign:gnome.org) on Matrix for guidance or answers to any questions :)

**Comment by Foldex** [comment]
Howdy.

I'll start off with saying that the current icon could use some work, as it's really just something I threw together in a few minutes to satisfy flathub requirements.
Not a designer, so it's a very basic and probably overtly literal melding of an Adwaita Switch and a game controller. Admittedly, it is also easily confused for a blue baseball. :shrug: 

In general I've been fairly truant with Gnome's HIG, treating this as a personal project rather than a strict adherent. (The name of the program being a fairly blatant tip off to this).
Kind of goes hand in hand with upstream, as that's more of a best effort to force Steam kicking and screaming into something remotely close to Adwaita, not perfectly emulate it.
(Since we're limited in how much we actually control of the Steam client, there's a fair number of hacks and compromises involved.)

That said certainly open to changing it, but icon design isn't my forte. I'd say feel free to prototype whatever you want on this.
I would prefer to keep discussions on this issue tracker if at all possible though.

**Comment by bragefuglseth** [comment]
Great! I'll start working on an icon now. If you want to, I can also open a PR with it when I'm done.
