### ISSUE TITLE
Steam Client Update Breakages

### ISSUE THREAD

**Issue by Foldex** [Foldex/AdwSteamGtk#63]
Steam client updated and broke a lot of things.
A lot of areas are going to be unthemed because of it.

~AdwSteamGtk is going to crash on launch. (Fixed in https://github.com/Foldex/AdwSteamGtk/commit/758d290eb687a2bfdbf9e99036f1b7938e3382fb, pending release)~
Fixed in Release [v0.6.11](https://github.com/Foldex/AdwSteamGtk/releases/tag/v0.6.11)

~Most upstream themes [are broken](https://github.com/tkashkin/Adwaita-for-Steam/issues/242#issuecomment-2099727774) right now and will not apply properly.~
Fixed in the upstream theme

**Comment by TempleOS-Enjoyer** [comment]
On Kubuntu LTS 22.04, the theme successfully applies (at least from the list you posted with supported colours), but only to my "settings" window. What a shame that these stupid updates broke it. :(

**Comment by Gpinchon** [comment]
"dots" window control doesn't work, only "default"

**Comment by Foldex** [comment]
>On Kubuntu LTS 22.04, the theme successfully applies (at least from the list you posted with supported colours), but only to my "settings" window.

Far as I know, the main parts of the client like the library should be functional.
I'd suggest an uninstall/reinstall, see if that can't help.

>What a shame that these stupid updates broke it. :(

Shrug, the theme is ultimately an unofficial hack that isnt officially supported, can't fault Valve for updating their client.

That said, this latest update does wind up being pretty hampering to theme development.
Instead of actual class names, most are now obfuscated.
Definitely doesn't make it any easier to keep working with going forward.
![image](https://github.com/Foldex/AdwSteamGtk/assets/47908676/8f6736ae-2ac2-478a-bb18-3f94c14bd7f0)

**Comment by Foldex** [comment]
Most of the worst bits of this are resolved, closing.

**Comment by RokeJulianLockhart** [comment]
> Instead of actual class names, most are now obfuscated. Definitely doesn't make it any easier to keep working with going forward.

@Foldex, do you expect that they're deliberately obfuscated, or merely automatically generated? If the latter, presumably, an upstream ticket could be filed. If so, I don't mind doing so, but might not be able to answer follow-ups from Valve.

**Comment by tkashkin** [comment]
@RokeJulianLockhart This was a deliberate decision from Valve.

https://store.steampowered.com/news/group/4397053/view/4134938965472819225:
> Modified CSS classnames to reduce package size and reduce feature leaks

They were already using the exact same hashes as a few characters at the end of old classnames, they just decided to remove the original human-readable classnames and kept the hashing algorithm the same, so old `steamdesktop_TopBar_3Z7VQ` became `_3Z7VQ1IMk4E3HsHvrkLNgo`.

They said they'll try to avoid changing classnames if possible and they are mostly unchanged since they were obfuscated. Some updates change some classnames, but it's not like they completely rename everything every update.
