### ISSUE TITLE
[Feature] Live update

### ISSUE THREAD

**Issue by zDyanTB** [Foldex/AdwSteamGtk#64]
Is there a way to implement a live update of the colors?
to use with matugen or pywal

**Comment by Foldex** [comment]
The upstream install script technically supports hot-reload, however it comes with some caveats that really don't make it well-suited for anything but quick testing.

- Steam has to be launched in dev mode for that to work.
- Hot reloading the patched CSS like that causes pretty heavy memory leaks in the steam client.
- There's good reasons not to want to use dev mode in general, which is why the installer patches files rather than use it. But if you did anyway, then you're probably better off using something like CSS Loader.

Of course, if there was a way to get hotload working without the above, then I'd be all for it.
